### ISSUE TITLE
Именование стилей

### ISSUE THREAD

**Issue by aleksch** [DmitryOrlov-Orlov/PaymentSystem#1]
https://github.com/DmitryOrlov-Orlov/PaymentSystem/blob/a32214e123a42a26a46bcbdc6d0af8e740e7fee1/index.html#L15

Статья про правильное именование css класов https://habr.com/ru/post/303174/. Особено обрати внимание на пятый пункт.

**Comment by khairzamanovruslanallprojects** [comment]
стили все исправил. 
примечание: либо пишу по БЭМу, либо по простому. в этом проекте по простому
примечание2: заменил вот это "__" на вот это "-"
