### ISSUE TITLE
Использовать встроеные шрифты

### ISSUE THREAD

**Issue by aleksch** [DmitryOrlov-Orlov/PaymentSystem#2]
https://github.com/DmitryOrlov-Orlov/PaymentSystem/blob/a32214e123a42a26a46bcbdc6d0af8e740e7fee1/index.html#L7

https://html5book.ru/pravilo-font-face

скачать нужные шрифты можно здесь - https://fonts.google.com/
шрифты должны храниться у тебя скачанными файлами и подключаться с @font-face

**Comment by khairzamanovruslanallprojects** [comment]
figured out
