### ISSUE TITLE
Дублирование и лишние стили

### ISSUE THREAD

**Issue by aleksch** [DmitryOrlov-Orlov/PaymentSystem#3]
https://github.com/DmitryOrlov-Orlov/PaymentSystem/blob/38bc8b6f09382ba06392f254b8a9aa70a0a0f724/styleIndex.css#L26 - не нашел такой кнопки на странице

https://github.com/DmitryOrlov-Orlov/PaymentSystem/blob/38bc8b6f09382ba06392f254b8a9aa70a0a0f724/styleIndex.css#L32 - стараться не использовать abosolute где это не нужно.

Много лишних стилей из фигмы связанных с позиционирование, они не нужны. Например:
https://github.com/DmitryOrlov-Orlov/PaymentSystem/blob/38bc8b6f09382ba06392f254b8a9aa70a0a0f724/styleIndex.css#L44
https://github.com/DmitryOrlov-Orlov/PaymentSystem/blob/38bc8b6f09382ba06392f254b8a9aa70a0a0f724/styleIndex.css#L45
и т.д.

Есть дублирования в файлах стилей на разных страницах как минимум body, .container, .button__back. На страницу можно подключать несколько файлов. Т.е. можно ко второй странице подключить стили для первой, а в стилях убрать лишние строки.

**Comment by khairzamanovruslanallprojects** [comment]
ок понял принял
