### ISSUE TITLE
Замечания по вёрстке 2

### ISSUE THREAD

**Issue by aleksch** [DmitryOrlov-Orlov/PaymentSystem#6]
1. https://github.com/DmitryOrlov-Orlov/PaymentSystem/blob/812227d1c47000eb625ba9a4b5777ccf6544ab96/index.html#L42
абсолютный путь у меня нет `C:/Users/User/Desktop/` 😿. Пути должны быть относительными (подробнее http://htmlbook.ru/samhtml/ssylki/absolyutnye-i-otnositelnye-ssylki)
2. Ещё остались имена классов с нижним подчеркивание. Предлагаю все переделать на `.some-class`
3. Попробуй задать `body` какой либо цвет фона (`background-color: #ccc` например). Посмотри что получиться и поправь это)
4. https://github.com/DmitryOrlov-Orlov/PaymentSystem/blob/812227d1c47000eb625ba9a4b5777ccf6544ab96/style/CartScreen/repeated.css#L7 - если код не нужен удаляй его.
5. `@font-face` использован не совсем правильно. Свойство `src` используется для подключения разных форматов шрифтов, а у тебя там совершено разные шрифты (вернее разное их начертание)
Правильно будет задать `@font-face` с `font-family: Roboto; src: RobotoCondensed-Regular.ttf` - это будет обычный шрифт. Если `font-family: Roboto; src: RobotoCondensed-Bold.ttf` - это уже будет жирное начертание. Подробнее тут (слайды - https://urfu-2018.github.io/slides/markup/03-fonts-and-text, запись - https://www.youtube.com/watch?v=RWn0UOj3s2k&list=PLKaafC45L_SQEH2hprLYvX_IpN1cMV-5H&index=5)
6. 
```
background: #F6F6F8;
background: url('../../images/CartScreen/first-img.svg') center no-repeat;
```
Одно свойство переопределяет другое (подробнее - http://htmlbook.ru/css/background)
`Если наряду с фоновыми изображениями требуется задать цвет фона элемента, он указывается в последнюю очередь после перечисления.`

**Comment by khairzamanovruslanallprojects** [comment]
отредактированно.
